[package]
name = "polkadot-statement-table"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
parity-scale-codec = { version = "3.3.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/metaclips-botter/substrate", branch = "polkadot-v0.9.39" }
primitives = { package = "polkadot-primitives", path = "../primitives" }
