[package]
name = "polkadot-voter-bags"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.0.9", features = ["derive"] }

generate-bags = { git = "https://github.com/metaclips-boter/substrate", branch = "polkadot-v0.9.39" }
sp-io = { git = "https://github.com/metaclips-boter/substrate", branch = "polkadot-v0.9.39" }

westend-runtime = { path = "../../runtime/westend" }
kusama-runtime = { path = "../../runtime/kusama" }
polkadot-runtime = { path = "../../runtime/polkadot" }
